FROM alpine:latest@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

LABEL "org.opencontainers.image.source"="https://github.com/pagopa/example-good-repo-packages"
LABEL "maintainer"="https://pagopa.it"
