FROM alpine:latest@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

LABEL "org.opencontainers.image.source"="https://github.com/pagopa/example-good-repo-packages"
LABEL "maintainer"="https://pagopa.it"
