name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

permissions:
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    environment: prod

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Log in to the Container registry
        id: docker_login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BOT_TOKEN }}

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # v2 is fixed version to run the attack scenario
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:v2
          labels: |
            maintainer=https://pagopa.it
            org.opencontainers.image.source=https://github.com/${{ github.repository }}